[package]
name = "jojodiff"
description = "Rust library for handling JojoDiff files, a diff utility for binary files."
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"

[dev-dependencies]
pretty_assertions = "1.4.1"
env_logger = "0.11.5"
